Generate with pre-trained model.

![dump/diffugpt_tokenizer.png](dump/diffugpt_tokenizer.png)

In [33]:
import tiktoken
import torch
from utils import get_annealing_mask
import model
from importlib import reload
reload(model)

# Load model
gpt = model.GPT2("local_config.json")

# Load Tokenizer
tokenizer = tiktoken.get_encoding("gpt2")

# Prompt
prompt = "Then, the man writes over the snow covering the window of a car, and a woman wearing winter clothes smiles. then"

mask_token = tokenizer.decode([10541])

input_ids = torch.tensor(
    [50256] + tokenizer.encode(prompt)
).unsqueeze(0)

xs = gpt.generate(input_ids, max_new_tokens=10)

for x in xs:
    out = tokenizer.decode(
        x[0].tolist()
    )
    out = out.replace(mask_token, "<mask>")
    print(out)

Modifying HF GPT2Model to accept custom attention mask...
Loading pre-trained DiffuGPT...
<All keys matched successfully>
tensor([[False, False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False, False,
         False, False, False, False, False,  True,  True, False, False, False,
         False, False, False, False, False]])
tensor([[False, False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False,  True,
          True, False, False, False, False]])
tensor([[False, False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False, False,
         False, False,  True, False,  True]])
tensor([[False, False, False,

## Test training pipeline

In [9]:
from datamodule import MemmapDataModule

dm = MemmapDataModule("local_config.json")

dm.setup()
dm.train_dataset[0]
dm.train_dataloader()